sonar.projectKey=IsabelBastos_unit-tests-jest-master
sonar.organization=isabelbastos
sonar.sources=src
sonar.tests=test
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=test/**,node_modules/**
